const fs = require('fs')
const inputParser = require('./inputParser')
const handyHaversacks = require('./handyHaversacks')

const handyHaversacksInput = fs.readFileSync('handy-haversacks-input').toString().split('.\n')
console.log(handyHaversacksInput)
const handyHaversacksRules = inputParser.parse(handyHaversacksInput)
console.log(handyHaversacksRules)
const bagsQuantity = handyHaversacks.countBagColors(handyHaversacksRules)
console.log(bagsQuantity)